[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wordie"
authors = [{name = "Eliot Finch"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/EliotFinch/codereview-doc-tutorial"
